# Generated by Django 5.1.1 on 2024-10-07 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='chais/')),
                ('dateAdded', models.DateTimeField(default=datetime.datetime(2024, 10, 7, 9, 59, 31, 309820, tzinfo=datetime.timezone.utc))),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('EL', 'ELACHI'), ('PL', 'PLAIN')], max_length=2)),
            ],
        ),
    ]
